# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - g21team

on:
  push:
    branches:
      - staging-test
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://g21be.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_d175b1851c6b4e81bbf31cbe96c8a86e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_871d6a802c8b4fa2aff13764cfc355ae }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: g21be.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d175b1851c6b4e81bbf31cbe96c8a86e }}/g21-fe:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'g21team'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_16d7220ddd234927961039c3e2d0c8ae }}
        images: 'g21be.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d175b1851c6b4e81bbf31cbe96c8a86e }}/g21-fe:${{ github.sha }}'